master:
  componentName: jenkins-master
  image: "jenkins/jenkins"
  imageTag: "2.179-alpine"

  overwriteConfig: true

  adminUser: admin
  adminPassword: admin

  installPlugins:
    - kubernetes:1.15.5
    - workflow-aggregator:2.6
    - workflow-job:2.32
    - credentials-binding:1.18
    - git:3.10.0
    - greenballs:1.15
    - google-login:1.4
    - role-strategy:2.9.0
    - locale:1.4

  servicePort: 8080
  serviceType: NodePort
  ingress:
    enabled: true
    hostName: jenkins.192.168.99.100.nip.io
    path: /

agent:
  enabled: true
  image: "jenkins/jnlp-slave"
  imageTag: "3.27-1-alpine"
  resources:
    requests:
      cpu: null
      memory: null
    limits:
      cpu: null
      memory: null

rbac:
  create: true
