apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment.properties
  namespace: jenkins
data:
  environment.properties: |
    env=ci
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repository
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
